version: '3'

services:
  tasky-api:
    image: tasky-api
    container_name: tasky-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - tasky-db
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@tasky-db:5432/tasky

  tasky-db:
    image: postgres:14
    container_name: tasky-db
    ports:
      - "5432:5432"
    volumes:
      - tasky-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=tasky
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  tasky-data:
  grafana-data: